apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sqldb
spec:
  type: bindings.mysql
  version: v1
  metadata:
    - name: url # Required, define DB connection in DSN format
      value: "root:WNe6CyED7Q@tcp(mysql-headless:3306)/mall_order?allowNativePasswords=true"